#!/usr/bin/env bash

_SHIMMER_ROOT=$(shimmer root)

command=$(basename $0)

versions=( $(ls $_SHIMMER_ROOT/shims/.index/$command) )

if [ ${#versions[@]} -eq 1 ]; then
    $_SHIMMER_ROOT/packages/${versions[0]}/bin/$command $*
else
    echo "Multiple versions can execute $command. IDK what to do :("
fi
