#!/usr/bin/env bash
# Usage: shimmer rehash
# Summary: Create any missing bin commands from downloaded packages with executables (bin)

set -e

SHIMMER_PACKAGES_DIR=$_SHIMMER_PACKAGES_DIR

SHIMS_DIR=$_SHIMMER_SHIMS_DIR

function generate_shim() {
    local libdir=$1
    local binname=$2

    binname=$(basename $binname)
    local libname=$(basename $libdir) # just the name of the lib (implicitly includes versioning info)
    [ -n "$_SHIMMER_CLI_TEST" ] && echo $binname, $libname && return 0

    if [ ! -f $_SHIMMER_SHIMS_DIR/$binname ]; then
        ln -s $_SHIMMER_ROOT/libexec/shim $_SHIMMER_SHIMS_DIR/$binname
        mkdir -p $_SHIMMER_SHIMS_DIR/.index/$binname
    fi
    touch $_SHIMMER_SHIMS_DIR/.index/$binname/$libname
}

for lib in $_SHIMMER_PACKAGES_DIR/*/; do
    lib=${lib%*/} # remove trailing slash so the line below looks a bit cleaner
    for bin in $lib/bin/*; do
        generate_shim $lib $bin
    done
done
